<a href="https://colab.research.google.com/github/Katerina2626/ML/blob/main/1_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Практическая работа 1-1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [ ]:
import numpy
numpy.__version__

'1.23.5'

2) Создать нулевой вектор размера 10

In [ ]:
import numpy as np
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [ ]:
np.full((1, 7), 7)

array([[7, 7, 7, 7, 7, 7, 7]])

4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
np.arange(10, 101, 2)

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
ar=np.random.randint(0, 10, (2,3))
#print(ar)
print(ar[::-1])

[[8 5 0]
 [7 7 0]]
[[7 7 0]
 [8 5 0]]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9 (от 0 до 9, это 10 цифр, в 9 позиций они не встанут)

In [ ]:
np.array([range(i, i + 3) for i in [0, 3, 6]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
import numpy as np
n = 4
b = np.zeros((n,n))
k=0
for i in range(4):
  for j in range(4):
    if j==k:
      b[i][j]=1
  k+=1
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
import numpy as np
n = 4
b=np.full((4,4), 7)
k=0
for i in range(4):
  for j in range(4):
    if j==k:
      b[i][j]=k+1
  k+=1
print(b)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
np.array([range(i, i + 5) for i in [0, 0,0,0,0]])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
from statistics import mean
ar=np.random.randint(0, 10, (10,10))
print(ar)
for i in range(10):
  sr=mean(ar[i])
  for j in range(10):
    ar[i][j]-=sr
print(ar)

[[5 2 4 8 2 4 4 2 2 3]
 [0 3 5 6 0 9 4 2 7 3]
 [9 5 7 4 7 0 0 7 4 3]
 [0 3 5 8 1 3 5 2 3 5]
 [8 2 9 2 7 4 5 7 0 2]
 [3 3 2 0 3 6 4 5 8 7]
 [3 2 3 0 0 9 8 6 6 4]
 [9 7 9 1 6 6 0 5 1 6]
 [3 5 0 8 8 0 7 0 0 2]
 [3 5 1 7 7 0 6 7 7 4]]
[[ 2 -1  1  5 -1  1  1 -1 -1  0]
 [-3  0  2  3 -3  6  1 -1  4  0]
 [ 5  1  3  0  3 -4 -4  3  0 -1]
 [-3  0  2  5 -2  0  2 -1  0  2]
 [ 4 -2  5 -2  3  0  1  3 -4 -2]
 [-1 -1 -2 -4 -1  2  0  1  4  3]
 [-1 -2 -1 -4 -4  5  4  2  2  0]
 [ 4  2  4 -4  1  1 -5  0 -4  1]
 [ 0  2 -3  5  5 -3  4 -3 -3 -1]
 [-1  1 -3  3  3 -4  2  3  3  0]]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [ ]:
from statistics import *
ar=np.random.randint(0, 10, (10,10))
print(ar)
print(" ")
for i in range(10):
  med=median([ar[4][i],ar[5][i]])
  for j in range(10):
    ar[j][i]-=med
print(ar)

[[5 8 0 7 1 1 4 4 7 5]
 [2 4 3 8 0 3 0 7 7 7]
 [5 9 0 9 0 1 3 1 0 9]
 [7 7 1 8 2 6 5 8 8 1]
 [8 6 2 1 2 3 0 4 4 7]
 [9 8 1 6 4 2 5 6 2 5]
 [6 1 2 1 5 6 0 1 5 6]
 [1 2 3 8 0 5 5 5 5 7]
 [9 1 7 5 9 3 8 5 2 8]
 [7 5 1 8 1 7 8 6 1 6]]
 
[[-3  1 -1  3 -2 -1  1 -1  4 -1]
 [-6 -3  1  4 -3  0 -2  2  4  1]
 [-3  2 -1  5 -3 -1  0 -4 -3  3]
 [-1  0  0  4 -1  3  2  3  5 -5]
 [ 0 -1  0 -2 -1  0 -2 -1  1  1]
 [ 0  1  0  2  1  0  2  1 -1 -1]
 [-2 -6  0 -2  2  3 -2 -4  2  0]
 [-7 -5  1  4 -3  2  2  0  2  1]
 [ 0 -6  5  1  6  0  5  0 -1  2]
 [-1 -2  0  4 -2  4  5  1 -2  0]]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [ ]:
"""from random import *
ar=np.random.randint(0, 10, (5,5))
mn=[]
mx=[]
print(ar)
for i in range(5):
  mn.append(min(ar[i]))
  mx.append(max(ar[i]))
new=np.zeros((5,2))
ar=np.append(ar,new,axis=1)

print(ar)
"""

[[2 5 0 8 6]
 [9 2 1 9 4]
 [8 0 7 0 1]
 [5 3 7 3 7]
 [0 4 3 0 2]]
[[2. 5. 0. 8. 6. 0. 0.]
 [9. 2. 1. 9. 4. 0. 0.]
 [8. 0. 7. 0. 1. 0. 0.]
 [5. 3. 7. 3. 7. 0. 0.]
 [0. 4. 3. 0. 2. 0. 0.]]


In [ ]:
# Создаем матрицу случайных чисел 5x5
ar = np.random.randint(0, 10, (5, 5))

# Создаем массивы для минимумов и максимумов по строкам
mn = np.min(ar, axis=1)
mx = np.max(ar, axis=1)

# Объединяем матрицу с массивами минимумов и максимумов
new_matrix = np.column_stack((ar, mn, mx))

print(new_matrix)

[[6 9 1 3 7 1 9]
 [6 4 2 9 6 2 9]
 [7 2 1 6 6 1 7]
 [8 3 8 1 8 1 8]
 [0 1 6 4 0 0 6]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу этого произведения.  

In [ ]:
ar=np.arange(1,51)
print(ar)
ch=ar[ar%2==0]
nch=ar[ar%2!=0]
ch=ch.reshape(5, 5)
nch=nch.reshape(5,5)
#print(ch)
#print(nch)
new = np.dot(ch, nch)
print(new)
#obr= np.linalg.inv(new) # я не знаю что не так, меня опять послали гуглить, гугл тоже не в курсе что он хочет :(
new2=np.array([new]).T
#print(np.linalg.inv(new))
#new2=new.T()
print(new2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
[[ 830  890  950 1010 1070]
 [1880 2040 2200 2360 2520]
 [2930 3190 3450 3710 3970]
 [3980 4340 4700 5060 5420]
 [5030 5490 5950 6410 6870]]
[[[ 830]
  [1880]
  [2930]
  [3980]
  [5030]]

 [[ 890]
  [2040]
  [3190]
  [4340]
  [5490]]

 [[ 950]
  [2200]
  [3450]
  [4700]
  [5950]]

 [[1010]
  [2360]
  [3710]
  [5060]
  [6410]]

 [[1070]
  [2520]
  [3970]
  [5420]
  [6870]]]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [ ]:
# создаем матрицу 8х8 заполненную нулями
ar = np.zeros((8, 8), dtype=int)
# используем срезы, чтобы заполнить каждую вторую строку и столбец нулями
ar[1::2, ::2] = 1
#print(ar)
ar[::2, 1::2] = 1

print(ar)

[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
